# azure-pipelines.yml
 
trigger:
- main  # Dispara o pipeline quando houver alterações no branch main
 
pool: Local_Agent
  #vmImage: 'ubuntu-latest'  # Você pode usar 'windows-latest' ou 'macos-latest' também
 
steps:
- script: echo "Hello, World! Hello, World!"
  displayName: 'Executar mensagem Hello World'