# azure-pipelines.yml
 
trigger:
- main  # Dispara o pipeline quando houver alterações no branch main
 
pool: 
  vmImage: 'windows-latest'  # Você pode usar 'ubuntu-latest', 'windows-latest' ou 'macos-latest' também
 
steps:
- script: echo "Hello, World! Hello, World!"
  displayName: 'Executar mensagem Hello World'